### ISSUE TITLE
m_safeCertContext is an invalid handle. 

### ISSUE THREAD

**Issue by previewtech** [kuujinbo/StackOverflow.iTextSharp.MVC.PdfSigner#2]
Hi,
I cloned your project and run.
Immediately got this error 'm_safeCertContext is an invalid handle. '

Stack trace is:

m_safeCertContext is an invalid handle. 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Security.Cryptography.CryptographicException: m_safeCertContext is an invalid handle.

Line 38:         {
Line 39:             X509Certificate2 cert = GetSignerCertificate();
Line 40:             return new BouncyCastle.X509CertificateParser()
Line 41:                 .ReadCertificate(cert.RawData);
Line 42:         }

[CryptographicException: m_safeCertContext is an invalid handle.]
   System.Security.Cryptography.X509Certificates.X509Certificate.ThrowIfContextInvalid() +12806742
   System.Security.Cryptography.X509Certificates.X509Certificate.get_RawData() +13
   System.Security.Cryptography.X509Certificates.X509Certificate.GetRawCertData() +9
   System.Security.Cryptography.X509Certificates.X509Certificate2.get_RawData() +12
   kuujinbo.StackOverflow.iTextSharp.MVC.PdfSigner.Services.WebCertificateReader.GetSigningCertificate() in D:\Work\StackOverflow.iTextSharp.MVC.PdfSigner\Services\WebCertificateReader.cs:40
   kuujinbo.StackOverflow.iTextSharp.MVC.PdfSigner.Services.WebSigner.PreSign(Byte[] pdfIn) in D:\Work\StackOverflow.iTextSharp.MVC.PdfSigner\Services\WebSigner.cs:238
   kuujinbo.StackOverflow.iTextSharp.MVC.PdfSigner.Controllers.HomeController.GetPreSignedTestReader() in D:\Work\StackOverflow.iTextSharp.MVC.PdfSigner\Controllers\HomeController.cs:48
   kuujinbo.StackOverflow.iTextSharp.MVC.PdfSigner.Controllers.HomeController.Index() in D:\Work\StackOverflow.iTextSharp.MVC.PdfSigner\Controllers\HomeController.cs:18
   lambda_method(Closure , ControllerBase , Object[] ) +61
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +228
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9748493
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +159

Kindly provide solution.

Thanks

**Comment by kuujinbo** [comment]
Hello,

That's the Exception thrown when the web server is not correctly configured to read client certificates. Visual Studio 2015 made breaking changes to the project config file, which is in the project sub-directory located here:

./.vs/config/applicationhost.config

Verified the changes work for VS 2015. Don't have access to any higher version right now, sorry. Also updated the README file in the source code.

**Comment by previewtech** [comment]
Working now.
Thanks.
